### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by goanpeca** [micro-manager/NDTiffStorage#130]
Hi team, in working on the conda forge package for the latest release

https://github.com/conda-forge/ndtiff-feedstock/pull/20

We noticed that the tarball is not including the `requirements.txt` file:
https://github.com/micro-manager/NDTiffStorage/blob/main/python/setup.py#L14

Which will result in a broken package when installing from a tarball 

I am going to add a dummy `requirements.txt` as the rest of the conda dependencies will be provided by the recipe `meta.yaml`. 

Using this sort of install procedure (relying on an external `requirements.txt`) file is not recommended. Could you look into other ways of specifying dependencies? for instance using a `setup.cfg` file as described [here](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html).

Cheers!

**Comment by henrypinkard** [comment]
Thanks for the explnantion @goanpeca! 

> On another note it seems the package is using `sortedcontainers` but it has not been declared as a dependency.

I think this was already addressed last week:

https://github.com/micro-manager/NDTiffStorage/pull/125

**Comment by goanpeca** [comment]
Cool, however this is the sort of code that is not recommended ;-)

```python
with open("requirements.txt") as f:
    requirements = f.read().splitlines()
```

We patch to remove that in the conda recipe anyway. Cheers

**Comment by bnavigator** [comment]
> We noticed that the tarball is not including the `requirements.txt` file: https://github.com/micro-manager/NDTiffStorage/blob/main/python/setup.py#L14

This is still an issue. #125 introduced the file, but it is not packaged.

**Comment by henrypinkard** [comment]
Maybe fixed in #176. Further improvement PRs welcome
